[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "HAL for the STM32F30x family of microcontrollers"
keywords = ["arm", "cortex-m", "stm32", "hal"]
license = "MIT OR Apache-2.0"
name = "stm32f30x-hal"
repository = "https://github.com/japaric/stm32f30x-hal"
version = "0.1.2"

[dependencies]
cortex-m = "0.4.0"
embedded-hal = "0.1.0"
nb = "0.1.0"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.stm32f30x]
version = "0.6.0"
git = "https://github.com/copterust/stm32f30x.git"

[features]
rt = ["stm32f30x/rt"]
